// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RihalChallenge.Data;

namespace RihalChallenge.Migrations
{
    [DbContext(typeof(RihalChallengeContext))]
    [Migration("20220315055729_Initial-commit")]
    partial class Initialcommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("RihalChallenge.Data.classes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ModifitedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("tb_classes");
                });

            modelBuilder.Entity("RihalChallenge.Data.countries", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ModifitedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("tb_countries");
                });

            modelBuilder.Entity("RihalChallenge.Data.students", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ModifitedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("class_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("country_Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("date_of_birth")
                        .HasColumnType("date");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("class_Id");

                    b.HasIndex("country_Id");

                    b.ToTable("tb_students");
                });

            modelBuilder.Entity("RihalChallenge.Data.students", b =>
                {
                    b.HasOne("RihalChallenge.Data.classes", "Classes")
                        .WithMany("Students")
                        .HasForeignKey("class_Id")
                        .HasConstraintName("FK_Students_Classes");

                    b.HasOne("RihalChallenge.Data.countries", "Countries")
                        .WithMany("Students")
                        .HasForeignKey("country_Id")
                        .HasConstraintName("FK_Students_Countries");

                    b.Navigation("Classes");

                    b.Navigation("Countries");
                });

            modelBuilder.Entity("RihalChallenge.Data.classes", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("RihalChallenge.Data.countries", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
